### ISSUE TITLE
Colors messed up after changing theme

### ISSUE THREAD

**Issue by viacommits** [tylerFowler/atom-midnight-oil#3]
When my theme changes, the colors gets messed up until I reopen the file.  See screenshots.

Right after theme switch, until a close and reopen the file:

![image](https://cloud.githubusercontent.com/assets/1824972/17233823/e82a8d5c-54f8-11e6-890b-aa5eae653506.png)

This is how it SHOULD look:

![image](https://cloud.githubusercontent.com/assets/1824972/17233829/f8ef2d00-54f8-11e6-89d7-c0b33b9d49a5.png)

**Comment by tylerFowler** [comment]
Yeah, that's actually a known issue with Atom, see issue [#9550](https://github.com/atom/atom/issues/9550), and read the README for this repo under 'Known Issues' for more details on that. This problem is usually fixed by closing that file and reopening it (creating a new Editor instance) or just restarting/reloading Atom. Annoying but I'm keeping an eye on that issue.

If restarting doesn't fix the problem let me know though and feel free to reopen.
